//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.4206
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace FET.POS.Model.DTO {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("OPT02_CreditCardProceRate_DTO")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class OPT02_CreditCardProceRate_DTO : global::System.Data.DataSet {
        
        private CREDIT_CARD_TYPEDataTable tableCREDIT_CARD_TYPE;
        
        private CREDIT_CARD_PROCE_RATEDataTable tableCREDIT_CARD_PROCE_RATE;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public OPT02_CreditCardProceRate_DTO() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected OPT02_CreditCardProceRate_DTO(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["CREDIT_CARD_TYPE"] != null)) {
                    base.Tables.Add(new CREDIT_CARD_TYPEDataTable(ds.Tables["CREDIT_CARD_TYPE"]));
                }
                if ((ds.Tables["CREDIT_CARD_PROCE_RATE"] != null)) {
                    base.Tables.Add(new CREDIT_CARD_PROCE_RATEDataTable(ds.Tables["CREDIT_CARD_PROCE_RATE"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public CREDIT_CARD_TYPEDataTable CREDIT_CARD_TYPE {
            get {
                return this.tableCREDIT_CARD_TYPE;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public CREDIT_CARD_PROCE_RATEDataTable CREDIT_CARD_PROCE_RATE {
            get {
                return this.tableCREDIT_CARD_PROCE_RATE;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            OPT02_CreditCardProceRate_DTO cln = ((OPT02_CreditCardProceRate_DTO)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["CREDIT_CARD_TYPE"] != null)) {
                    base.Tables.Add(new CREDIT_CARD_TYPEDataTable(ds.Tables["CREDIT_CARD_TYPE"]));
                }
                if ((ds.Tables["CREDIT_CARD_PROCE_RATE"] != null)) {
                    base.Tables.Add(new CREDIT_CARD_PROCE_RATEDataTable(ds.Tables["CREDIT_CARD_PROCE_RATE"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableCREDIT_CARD_TYPE = ((CREDIT_CARD_TYPEDataTable)(base.Tables["CREDIT_CARD_TYPE"]));
            if ((initTable == true)) {
                if ((this.tableCREDIT_CARD_TYPE != null)) {
                    this.tableCREDIT_CARD_TYPE.InitVars();
                }
            }
            this.tableCREDIT_CARD_PROCE_RATE = ((CREDIT_CARD_PROCE_RATEDataTable)(base.Tables["CREDIT_CARD_PROCE_RATE"]));
            if ((initTable == true)) {
                if ((this.tableCREDIT_CARD_PROCE_RATE != null)) {
                    this.tableCREDIT_CARD_PROCE_RATE.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "OPT02_CreditCardProceRate_DTO";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/OPT02_CREDITCARD_PROCERATE.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableCREDIT_CARD_TYPE = new CREDIT_CARD_TYPEDataTable();
            base.Tables.Add(this.tableCREDIT_CARD_TYPE);
            this.tableCREDIT_CARD_PROCE_RATE = new CREDIT_CARD_PROCE_RATEDataTable();
            base.Tables.Add(this.tableCREDIT_CARD_PROCE_RATE);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeCREDIT_CARD_TYPE() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeCREDIT_CARD_PROCE_RATE() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            OPT02_CreditCardProceRate_DTO ds = new OPT02_CreditCardProceRate_DTO();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void CREDIT_CARD_TYPERowChangeEventHandler(object sender, CREDIT_CARD_TYPERowChangeEvent e);
        
        public delegate void CREDIT_CARD_PROCE_RATERowChangeEventHandler(object sender, CREDIT_CARD_PROCE_RATERowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class CREDIT_CARD_TYPEDataTable : global::System.Data.TypedTableBase<CREDIT_CARD_TYPERow> {
            
            private global::System.Data.DataColumn columnCREDIT_CARD_TYPE_ID;
            
            private global::System.Data.DataColumn columnCREDIT_CARD_TYPE_NO;
            
            private global::System.Data.DataColumn columnCREDID_CARD_TYPE_NAME;
            
            private global::System.Data.DataColumn columnCREATE_USER;
            
            private global::System.Data.DataColumn columnCREATE_DTM;
            
            private global::System.Data.DataColumn columnMODI_USER;
            
            private global::System.Data.DataColumn columnMODI_DTM;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CREDIT_CARD_TYPEDataTable() {
                this.TableName = "CREDIT_CARD_TYPE";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal CREDIT_CARD_TYPEDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected CREDIT_CARD_TYPEDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CREDIT_CARD_TYPE_IDColumn {
                get {
                    return this.columnCREDIT_CARD_TYPE_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CREDIT_CARD_TYPE_NOColumn {
                get {
                    return this.columnCREDIT_CARD_TYPE_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CREDID_CARD_TYPE_NAMEColumn {
                get {
                    return this.columnCREDID_CARD_TYPE_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CREATE_USERColumn {
                get {
                    return this.columnCREATE_USER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CREATE_DTMColumn {
                get {
                    return this.columnCREATE_DTM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MODI_USERColumn {
                get {
                    return this.columnMODI_USER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MODI_DTMColumn {
                get {
                    return this.columnMODI_DTM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CREDIT_CARD_TYPERow this[int index] {
                get {
                    return ((CREDIT_CARD_TYPERow)(this.Rows[index]));
                }
            }
            
            public event CREDIT_CARD_TYPERowChangeEventHandler CREDIT_CARD_TYPERowChanging;
            
            public event CREDIT_CARD_TYPERowChangeEventHandler CREDIT_CARD_TYPERowChanged;
            
            public event CREDIT_CARD_TYPERowChangeEventHandler CREDIT_CARD_TYPERowDeleting;
            
            public event CREDIT_CARD_TYPERowChangeEventHandler CREDIT_CARD_TYPERowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddCREDIT_CARD_TYPERow(CREDIT_CARD_TYPERow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CREDIT_CARD_TYPERow AddCREDIT_CARD_TYPERow(string CREDIT_CARD_TYPE_ID, string CREDIT_CARD_TYPE_NO, string CREDID_CARD_TYPE_NAME, string CREATE_USER, System.DateTime CREATE_DTM, string MODI_USER, System.DateTime MODI_DTM) {
                CREDIT_CARD_TYPERow rowCREDIT_CARD_TYPERow = ((CREDIT_CARD_TYPERow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        CREDIT_CARD_TYPE_ID,
                        CREDIT_CARD_TYPE_NO,
                        CREDID_CARD_TYPE_NAME,
                        CREATE_USER,
                        CREATE_DTM,
                        MODI_USER,
                        MODI_DTM};
                rowCREDIT_CARD_TYPERow.ItemArray = columnValuesArray;
                this.Rows.Add(rowCREDIT_CARD_TYPERow);
                return rowCREDIT_CARD_TYPERow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CREDIT_CARD_TYPERow FindByCREDIT_CARD_TYPE_ID(string CREDIT_CARD_TYPE_ID) {
                return ((CREDIT_CARD_TYPERow)(this.Rows.Find(new object[] {
                            CREDIT_CARD_TYPE_ID})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                CREDIT_CARD_TYPEDataTable cln = ((CREDIT_CARD_TYPEDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new CREDIT_CARD_TYPEDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnCREDIT_CARD_TYPE_ID = base.Columns["CREDIT_CARD_TYPE_ID"];
                this.columnCREDIT_CARD_TYPE_NO = base.Columns["CREDIT_CARD_TYPE_NO"];
                this.columnCREDID_CARD_TYPE_NAME = base.Columns["CREDID_CARD_TYPE_NAME"];
                this.columnCREATE_USER = base.Columns["CREATE_USER"];
                this.columnCREATE_DTM = base.Columns["CREATE_DTM"];
                this.columnMODI_USER = base.Columns["MODI_USER"];
                this.columnMODI_DTM = base.Columns["MODI_DTM"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnCREDIT_CARD_TYPE_ID = new global::System.Data.DataColumn("CREDIT_CARD_TYPE_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREDIT_CARD_TYPE_ID);
                this.columnCREDIT_CARD_TYPE_NO = new global::System.Data.DataColumn("CREDIT_CARD_TYPE_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREDIT_CARD_TYPE_NO);
                this.columnCREDID_CARD_TYPE_NAME = new global::System.Data.DataColumn("CREDID_CARD_TYPE_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREDID_CARD_TYPE_NAME);
                this.columnCREATE_USER = new global::System.Data.DataColumn("CREATE_USER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREATE_USER);
                this.columnCREATE_DTM = new global::System.Data.DataColumn("CREATE_DTM", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREATE_DTM);
                this.columnMODI_USER = new global::System.Data.DataColumn("MODI_USER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMODI_USER);
                this.columnMODI_DTM = new global::System.Data.DataColumn("MODI_DTM", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMODI_DTM);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnCREDIT_CARD_TYPE_ID}, true));
                this.columnCREDIT_CARD_TYPE_ID.AllowDBNull = false;
                this.columnCREDIT_CARD_TYPE_ID.Unique = true;
                this.columnCREDIT_CARD_TYPE_ID.MaxLength = 32;
                this.columnCREDIT_CARD_TYPE_NO.AllowDBNull = false;
                this.columnCREDIT_CARD_TYPE_NO.MaxLength = 50;
                this.columnCREDID_CARD_TYPE_NAME.AllowDBNull = false;
                this.columnCREDID_CARD_TYPE_NAME.MaxLength = 50;
                this.columnCREATE_USER.MaxLength = 50;
                this.columnCREATE_DTM.AllowDBNull = false;
                this.columnMODI_USER.AllowDBNull = false;
                this.columnMODI_USER.MaxLength = 50;
                this.columnMODI_DTM.AllowDBNull = false;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CREDIT_CARD_TYPERow NewCREDIT_CARD_TYPERow() {
                return ((CREDIT_CARD_TYPERow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new CREDIT_CARD_TYPERow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(CREDIT_CARD_TYPERow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.CREDIT_CARD_TYPERowChanged != null)) {
                    this.CREDIT_CARD_TYPERowChanged(this, new CREDIT_CARD_TYPERowChangeEvent(((CREDIT_CARD_TYPERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.CREDIT_CARD_TYPERowChanging != null)) {
                    this.CREDIT_CARD_TYPERowChanging(this, new CREDIT_CARD_TYPERowChangeEvent(((CREDIT_CARD_TYPERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.CREDIT_CARD_TYPERowDeleted != null)) {
                    this.CREDIT_CARD_TYPERowDeleted(this, new CREDIT_CARD_TYPERowChangeEvent(((CREDIT_CARD_TYPERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.CREDIT_CARD_TYPERowDeleting != null)) {
                    this.CREDIT_CARD_TYPERowDeleting(this, new CREDIT_CARD_TYPERowChangeEvent(((CREDIT_CARD_TYPERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveCREDIT_CARD_TYPERow(CREDIT_CARD_TYPERow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                OPT02_CreditCardProceRate_DTO ds = new OPT02_CreditCardProceRate_DTO();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "CREDIT_CARD_TYPEDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class CREDIT_CARD_PROCE_RATEDataTable : global::System.Data.TypedTableBase<CREDIT_CARD_PROCE_RATERow> {
            
            private global::System.Data.DataColumn columnCCPR_ID;
            
            private global::System.Data.DataColumn columnCREDIT_CARD_TYPE_ID;
            
            private global::System.Data.DataColumn columnCHARGE_RATE;
            
            private global::System.Data.DataColumn columnS_DATE;
            
            private global::System.Data.DataColumn columnE_DATE;
            
            private global::System.Data.DataColumn columnCREATE_USER;
            
            private global::System.Data.DataColumn columnCREATE_DTM;
            
            private global::System.Data.DataColumn columnMODI_USER;
            
            private global::System.Data.DataColumn columnMODI_DTM;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CREDIT_CARD_PROCE_RATEDataTable() {
                this.TableName = "CREDIT_CARD_PROCE_RATE";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal CREDIT_CARD_PROCE_RATEDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected CREDIT_CARD_PROCE_RATEDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CCPR_IDColumn {
                get {
                    return this.columnCCPR_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CREDIT_CARD_TYPE_IDColumn {
                get {
                    return this.columnCREDIT_CARD_TYPE_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CHARGE_RATEColumn {
                get {
                    return this.columnCHARGE_RATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn S_DATEColumn {
                get {
                    return this.columnS_DATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn E_DATEColumn {
                get {
                    return this.columnE_DATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CREATE_USERColumn {
                get {
                    return this.columnCREATE_USER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CREATE_DTMColumn {
                get {
                    return this.columnCREATE_DTM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MODI_USERColumn {
                get {
                    return this.columnMODI_USER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MODI_DTMColumn {
                get {
                    return this.columnMODI_DTM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CREDIT_CARD_PROCE_RATERow this[int index] {
                get {
                    return ((CREDIT_CARD_PROCE_RATERow)(this.Rows[index]));
                }
            }
            
            public event CREDIT_CARD_PROCE_RATERowChangeEventHandler CREDIT_CARD_PROCE_RATERowChanging;
            
            public event CREDIT_CARD_PROCE_RATERowChangeEventHandler CREDIT_CARD_PROCE_RATERowChanged;
            
            public event CREDIT_CARD_PROCE_RATERowChangeEventHandler CREDIT_CARD_PROCE_RATERowDeleting;
            
            public event CREDIT_CARD_PROCE_RATERowChangeEventHandler CREDIT_CARD_PROCE_RATERowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddCREDIT_CARD_PROCE_RATERow(CREDIT_CARD_PROCE_RATERow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CREDIT_CARD_PROCE_RATERow AddCREDIT_CARD_PROCE_RATERow(string CCPR_ID, string CREDIT_CARD_TYPE_ID, decimal CHARGE_RATE, System.DateTime S_DATE, System.DateTime E_DATE, string CREATE_USER, System.DateTime CREATE_DTM, string MODI_USER, System.DateTime MODI_DTM) {
                CREDIT_CARD_PROCE_RATERow rowCREDIT_CARD_PROCE_RATERow = ((CREDIT_CARD_PROCE_RATERow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        CCPR_ID,
                        CREDIT_CARD_TYPE_ID,
                        CHARGE_RATE,
                        S_DATE,
                        E_DATE,
                        CREATE_USER,
                        CREATE_DTM,
                        MODI_USER,
                        MODI_DTM};
                rowCREDIT_CARD_PROCE_RATERow.ItemArray = columnValuesArray;
                this.Rows.Add(rowCREDIT_CARD_PROCE_RATERow);
                return rowCREDIT_CARD_PROCE_RATERow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CREDIT_CARD_PROCE_RATERow FindByCCPR_ID(string CCPR_ID) {
                return ((CREDIT_CARD_PROCE_RATERow)(this.Rows.Find(new object[] {
                            CCPR_ID})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                CREDIT_CARD_PROCE_RATEDataTable cln = ((CREDIT_CARD_PROCE_RATEDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new CREDIT_CARD_PROCE_RATEDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnCCPR_ID = base.Columns["CCPR_ID"];
                this.columnCREDIT_CARD_TYPE_ID = base.Columns["CREDIT_CARD_TYPE_ID"];
                this.columnCHARGE_RATE = base.Columns["CHARGE_RATE"];
                this.columnS_DATE = base.Columns["S_DATE"];
                this.columnE_DATE = base.Columns["E_DATE"];
                this.columnCREATE_USER = base.Columns["CREATE_USER"];
                this.columnCREATE_DTM = base.Columns["CREATE_DTM"];
                this.columnMODI_USER = base.Columns["MODI_USER"];
                this.columnMODI_DTM = base.Columns["MODI_DTM"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnCCPR_ID = new global::System.Data.DataColumn("CCPR_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCCPR_ID);
                this.columnCREDIT_CARD_TYPE_ID = new global::System.Data.DataColumn("CREDIT_CARD_TYPE_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREDIT_CARD_TYPE_ID);
                this.columnCHARGE_RATE = new global::System.Data.DataColumn("CHARGE_RATE", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCHARGE_RATE);
                this.columnS_DATE = new global::System.Data.DataColumn("S_DATE", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnS_DATE);
                this.columnE_DATE = new global::System.Data.DataColumn("E_DATE", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnE_DATE);
                this.columnCREATE_USER = new global::System.Data.DataColumn("CREATE_USER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREATE_USER);
                this.columnCREATE_DTM = new global::System.Data.DataColumn("CREATE_DTM", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREATE_DTM);
                this.columnMODI_USER = new global::System.Data.DataColumn("MODI_USER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMODI_USER);
                this.columnMODI_DTM = new global::System.Data.DataColumn("MODI_DTM", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMODI_DTM);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnCCPR_ID}, true));
                this.columnCCPR_ID.AllowDBNull = false;
                this.columnCCPR_ID.Unique = true;
                this.columnCCPR_ID.MaxLength = 32;
                this.columnCREDIT_CARD_TYPE_ID.MaxLength = 32;
                this.columnCHARGE_RATE.AllowDBNull = false;
                this.columnS_DATE.AllowDBNull = false;
                this.columnCREATE_USER.AllowDBNull = false;
                this.columnCREATE_USER.MaxLength = 50;
                this.columnCREATE_DTM.AllowDBNull = false;
                this.columnMODI_USER.MaxLength = 50;
                this.columnMODI_DTM.AllowDBNull = false;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CREDIT_CARD_PROCE_RATERow NewCREDIT_CARD_PROCE_RATERow() {
                return ((CREDIT_CARD_PROCE_RATERow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new CREDIT_CARD_PROCE_RATERow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(CREDIT_CARD_PROCE_RATERow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.CREDIT_CARD_PROCE_RATERowChanged != null)) {
                    this.CREDIT_CARD_PROCE_RATERowChanged(this, new CREDIT_CARD_PROCE_RATERowChangeEvent(((CREDIT_CARD_PROCE_RATERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.CREDIT_CARD_PROCE_RATERowChanging != null)) {
                    this.CREDIT_CARD_PROCE_RATERowChanging(this, new CREDIT_CARD_PROCE_RATERowChangeEvent(((CREDIT_CARD_PROCE_RATERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.CREDIT_CARD_PROCE_RATERowDeleted != null)) {
                    this.CREDIT_CARD_PROCE_RATERowDeleted(this, new CREDIT_CARD_PROCE_RATERowChangeEvent(((CREDIT_CARD_PROCE_RATERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.CREDIT_CARD_PROCE_RATERowDeleting != null)) {
                    this.CREDIT_CARD_PROCE_RATERowDeleting(this, new CREDIT_CARD_PROCE_RATERowChangeEvent(((CREDIT_CARD_PROCE_RATERow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveCREDIT_CARD_PROCE_RATERow(CREDIT_CARD_PROCE_RATERow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                OPT02_CreditCardProceRate_DTO ds = new OPT02_CreditCardProceRate_DTO();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "CREDIT_CARD_PROCE_RATEDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class CREDIT_CARD_TYPERow : global::System.Data.DataRow {
            
            private CREDIT_CARD_TYPEDataTable tableCREDIT_CARD_TYPE;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal CREDIT_CARD_TYPERow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableCREDIT_CARD_TYPE = ((CREDIT_CARD_TYPEDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CREDIT_CARD_TYPE_ID {
                get {
                    return ((string)(this[this.tableCREDIT_CARD_TYPE.CREDIT_CARD_TYPE_IDColumn]));
                }
                set {
                    this[this.tableCREDIT_CARD_TYPE.CREDIT_CARD_TYPE_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CREDIT_CARD_TYPE_NO {
                get {
                    return ((string)(this[this.tableCREDIT_CARD_TYPE.CREDIT_CARD_TYPE_NOColumn]));
                }
                set {
                    this[this.tableCREDIT_CARD_TYPE.CREDIT_CARD_TYPE_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CREDID_CARD_TYPE_NAME {
                get {
                    return ((string)(this[this.tableCREDIT_CARD_TYPE.CREDID_CARD_TYPE_NAMEColumn]));
                }
                set {
                    this[this.tableCREDIT_CARD_TYPE.CREDID_CARD_TYPE_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CREATE_USER {
                get {
                    try {
                        return ((string)(this[this.tableCREDIT_CARD_TYPE.CREATE_USERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'CREDIT_CARD_TYPE\' 中資料行 \'CREATE_USER\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableCREDIT_CARD_TYPE.CREATE_USERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime CREATE_DTM {
                get {
                    return ((global::System.DateTime)(this[this.tableCREDIT_CARD_TYPE.CREATE_DTMColumn]));
                }
                set {
                    this[this.tableCREDIT_CARD_TYPE.CREATE_DTMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string MODI_USER {
                get {
                    return ((string)(this[this.tableCREDIT_CARD_TYPE.MODI_USERColumn]));
                }
                set {
                    this[this.tableCREDIT_CARD_TYPE.MODI_USERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime MODI_DTM {
                get {
                    return ((global::System.DateTime)(this[this.tableCREDIT_CARD_TYPE.MODI_DTMColumn]));
                }
                set {
                    this[this.tableCREDIT_CARD_TYPE.MODI_DTMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCREATE_USERNull() {
                return this.IsNull(this.tableCREDIT_CARD_TYPE.CREATE_USERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCREATE_USERNull() {
                this[this.tableCREDIT_CARD_TYPE.CREATE_USERColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class CREDIT_CARD_PROCE_RATERow : global::System.Data.DataRow {
            
            private CREDIT_CARD_PROCE_RATEDataTable tableCREDIT_CARD_PROCE_RATE;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal CREDIT_CARD_PROCE_RATERow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableCREDIT_CARD_PROCE_RATE = ((CREDIT_CARD_PROCE_RATEDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CCPR_ID {
                get {
                    return ((string)(this[this.tableCREDIT_CARD_PROCE_RATE.CCPR_IDColumn]));
                }
                set {
                    this[this.tableCREDIT_CARD_PROCE_RATE.CCPR_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CREDIT_CARD_TYPE_ID {
                get {
                    try {
                        return ((string)(this[this.tableCREDIT_CARD_PROCE_RATE.CREDIT_CARD_TYPE_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'CREDIT_CARD_PROCE_RATE\' 中資料行 \'CREDIT_CARD_TYPE_ID\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableCREDIT_CARD_PROCE_RATE.CREDIT_CARD_TYPE_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal CHARGE_RATE {
                get {
                    return ((decimal)(this[this.tableCREDIT_CARD_PROCE_RATE.CHARGE_RATEColumn]));
                }
                set {
                    this[this.tableCREDIT_CARD_PROCE_RATE.CHARGE_RATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime S_DATE {
                get {
                    return ((global::System.DateTime)(this[this.tableCREDIT_CARD_PROCE_RATE.S_DATEColumn]));
                }
                set {
                    this[this.tableCREDIT_CARD_PROCE_RATE.S_DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime E_DATE {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableCREDIT_CARD_PROCE_RATE.E_DATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'CREDIT_CARD_PROCE_RATE\' 中資料行 \'E_DATE\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableCREDIT_CARD_PROCE_RATE.E_DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CREATE_USER {
                get {
                    return ((string)(this[this.tableCREDIT_CARD_PROCE_RATE.CREATE_USERColumn]));
                }
                set {
                    this[this.tableCREDIT_CARD_PROCE_RATE.CREATE_USERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime CREATE_DTM {
                get {
                    return ((global::System.DateTime)(this[this.tableCREDIT_CARD_PROCE_RATE.CREATE_DTMColumn]));
                }
                set {
                    this[this.tableCREDIT_CARD_PROCE_RATE.CREATE_DTMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string MODI_USER {
                get {
                    try {
                        return ((string)(this[this.tableCREDIT_CARD_PROCE_RATE.MODI_USERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'CREDIT_CARD_PROCE_RATE\' 中資料行 \'MODI_USER\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableCREDIT_CARD_PROCE_RATE.MODI_USERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime MODI_DTM {
                get {
                    return ((global::System.DateTime)(this[this.tableCREDIT_CARD_PROCE_RATE.MODI_DTMColumn]));
                }
                set {
                    this[this.tableCREDIT_CARD_PROCE_RATE.MODI_DTMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCREDIT_CARD_TYPE_IDNull() {
                return this.IsNull(this.tableCREDIT_CARD_PROCE_RATE.CREDIT_CARD_TYPE_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCREDIT_CARD_TYPE_IDNull() {
                this[this.tableCREDIT_CARD_PROCE_RATE.CREDIT_CARD_TYPE_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsE_DATENull() {
                return this.IsNull(this.tableCREDIT_CARD_PROCE_RATE.E_DATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetE_DATENull() {
                this[this.tableCREDIT_CARD_PROCE_RATE.E_DATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMODI_USERNull() {
                return this.IsNull(this.tableCREDIT_CARD_PROCE_RATE.MODI_USERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMODI_USERNull() {
                this[this.tableCREDIT_CARD_PROCE_RATE.MODI_USERColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class CREDIT_CARD_TYPERowChangeEvent : global::System.EventArgs {
            
            private CREDIT_CARD_TYPERow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CREDIT_CARD_TYPERowChangeEvent(CREDIT_CARD_TYPERow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CREDIT_CARD_TYPERow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class CREDIT_CARD_PROCE_RATERowChangeEvent : global::System.EventArgs {
            
            private CREDIT_CARD_PROCE_RATERow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CREDIT_CARD_PROCE_RATERowChangeEvent(CREDIT_CARD_PROCE_RATERow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CREDIT_CARD_PROCE_RATERow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591