//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.4952
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace FET.POS.Model.DTO {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("PROD_IMEI_DTO")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class PROD_IMEI_DTO : global::System.Data.DataSet {
        
        private INV_APPRO_IMEIDataTable tableINV_APPRO_IMEI;
        
        private INV_APPRO_IMEI_TEMPDataTable tableINV_APPRO_IMEI_TEMP;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PROD_IMEI_DTO() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected PROD_IMEI_DTO(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["INV_APPRO_IMEI"] != null)) {
                    base.Tables.Add(new INV_APPRO_IMEIDataTable(ds.Tables["INV_APPRO_IMEI"]));
                }
                if ((ds.Tables["INV_APPRO_IMEI_TEMP"] != null)) {
                    base.Tables.Add(new INV_APPRO_IMEI_TEMPDataTable(ds.Tables["INV_APPRO_IMEI_TEMP"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public INV_APPRO_IMEIDataTable INV_APPRO_IMEI {
            get {
                return this.tableINV_APPRO_IMEI;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public INV_APPRO_IMEI_TEMPDataTable INV_APPRO_IMEI_TEMP {
            get {
                return this.tableINV_APPRO_IMEI_TEMP;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            PROD_IMEI_DTO cln = ((PROD_IMEI_DTO)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["INV_APPRO_IMEI"] != null)) {
                    base.Tables.Add(new INV_APPRO_IMEIDataTable(ds.Tables["INV_APPRO_IMEI"]));
                }
                if ((ds.Tables["INV_APPRO_IMEI_TEMP"] != null)) {
                    base.Tables.Add(new INV_APPRO_IMEI_TEMPDataTable(ds.Tables["INV_APPRO_IMEI_TEMP"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableINV_APPRO_IMEI = ((INV_APPRO_IMEIDataTable)(base.Tables["INV_APPRO_IMEI"]));
            if ((initTable == true)) {
                if ((this.tableINV_APPRO_IMEI != null)) {
                    this.tableINV_APPRO_IMEI.InitVars();
                }
            }
            this.tableINV_APPRO_IMEI_TEMP = ((INV_APPRO_IMEI_TEMPDataTable)(base.Tables["INV_APPRO_IMEI_TEMP"]));
            if ((initTable == true)) {
                if ((this.tableINV_APPRO_IMEI_TEMP != null)) {
                    this.tableINV_APPRO_IMEI_TEMP.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "PROD_IMEI_DTO";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/PROD_IMEI_DTO.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableINV_APPRO_IMEI = new INV_APPRO_IMEIDataTable();
            base.Tables.Add(this.tableINV_APPRO_IMEI);
            this.tableINV_APPRO_IMEI_TEMP = new INV_APPRO_IMEI_TEMPDataTable();
            base.Tables.Add(this.tableINV_APPRO_IMEI_TEMP);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeINV_APPRO_IMEI() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeINV_APPRO_IMEI_TEMP() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            PROD_IMEI_DTO ds = new PROD_IMEI_DTO();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void INV_APPRO_IMEIRowChangeEventHandler(object sender, INV_APPRO_IMEIRowChangeEvent e);
        
        public delegate void INV_APPRO_IMEI_TEMPRowChangeEventHandler(object sender, INV_APPRO_IMEI_TEMPRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class INV_APPRO_IMEIDataTable : global::System.Data.TypedTableBase<INV_APPRO_IMEIRow> {
            
            private global::System.Data.DataColumn columnINV_APPRO_IMEI_ID;
            
            private global::System.Data.DataColumn columnIMEI;
            
            private global::System.Data.DataColumn columnCREATE_USER;
            
            private global::System.Data.DataColumn columnCREATE_DTM;
            
            private global::System.Data.DataColumn columnMODI_DTM;
            
            private global::System.Data.DataColumn columnMODI_USER;
            
            private global::System.Data.DataColumn columnPRODNO;
            
            private global::System.Data.DataColumn columnPO_OE_NO;
            
            private global::System.Data.DataColumn columnINV_APPROVAL_D_ID;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public INV_APPRO_IMEIDataTable() {
                this.TableName = "INV_APPRO_IMEI";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal INV_APPRO_IMEIDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected INV_APPRO_IMEIDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn INV_APPRO_IMEI_IDColumn {
                get {
                    return this.columnINV_APPRO_IMEI_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IMEIColumn {
                get {
                    return this.columnIMEI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CREATE_USERColumn {
                get {
                    return this.columnCREATE_USER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CREATE_DTMColumn {
                get {
                    return this.columnCREATE_DTM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MODI_DTMColumn {
                get {
                    return this.columnMODI_DTM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MODI_USERColumn {
                get {
                    return this.columnMODI_USER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PRODNOColumn {
                get {
                    return this.columnPRODNO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PO_OE_NOColumn {
                get {
                    return this.columnPO_OE_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn INV_APPROVAL_D_IDColumn {
                get {
                    return this.columnINV_APPROVAL_D_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public INV_APPRO_IMEIRow this[int index] {
                get {
                    return ((INV_APPRO_IMEIRow)(this.Rows[index]));
                }
            }
            
            public event INV_APPRO_IMEIRowChangeEventHandler INV_APPRO_IMEIRowChanging;
            
            public event INV_APPRO_IMEIRowChangeEventHandler INV_APPRO_IMEIRowChanged;
            
            public event INV_APPRO_IMEIRowChangeEventHandler INV_APPRO_IMEIRowDeleting;
            
            public event INV_APPRO_IMEIRowChangeEventHandler INV_APPRO_IMEIRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddINV_APPRO_IMEIRow(INV_APPRO_IMEIRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public INV_APPRO_IMEIRow AddINV_APPRO_IMEIRow(string INV_APPRO_IMEI_ID, string IMEI, string CREATE_USER, System.DateTime CREATE_DTM, System.DateTime MODI_DTM, string MODI_USER, string PRODNO, string PO_OE_NO, string INV_APPROVAL_D_ID) {
                INV_APPRO_IMEIRow rowINV_APPRO_IMEIRow = ((INV_APPRO_IMEIRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        INV_APPRO_IMEI_ID,
                        IMEI,
                        CREATE_USER,
                        CREATE_DTM,
                        MODI_DTM,
                        MODI_USER,
                        PRODNO,
                        PO_OE_NO,
                        INV_APPROVAL_D_ID};
                rowINV_APPRO_IMEIRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowINV_APPRO_IMEIRow);
                return rowINV_APPRO_IMEIRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public INV_APPRO_IMEIRow FindByINV_APPRO_IMEI_ID(string INV_APPRO_IMEI_ID) {
                return ((INV_APPRO_IMEIRow)(this.Rows.Find(new object[] {
                            INV_APPRO_IMEI_ID})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                INV_APPRO_IMEIDataTable cln = ((INV_APPRO_IMEIDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new INV_APPRO_IMEIDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnINV_APPRO_IMEI_ID = base.Columns["INV_APPRO_IMEI_ID"];
                this.columnIMEI = base.Columns["IMEI"];
                this.columnCREATE_USER = base.Columns["CREATE_USER"];
                this.columnCREATE_DTM = base.Columns["CREATE_DTM"];
                this.columnMODI_DTM = base.Columns["MODI_DTM"];
                this.columnMODI_USER = base.Columns["MODI_USER"];
                this.columnPRODNO = base.Columns["PRODNO"];
                this.columnPO_OE_NO = base.Columns["PO_OE_NO"];
                this.columnINV_APPROVAL_D_ID = base.Columns["INV_APPROVAL_D_ID"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnINV_APPRO_IMEI_ID = new global::System.Data.DataColumn("INV_APPRO_IMEI_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINV_APPRO_IMEI_ID);
                this.columnIMEI = new global::System.Data.DataColumn("IMEI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIMEI);
                this.columnCREATE_USER = new global::System.Data.DataColumn("CREATE_USER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREATE_USER);
                this.columnCREATE_DTM = new global::System.Data.DataColumn("CREATE_DTM", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREATE_DTM);
                this.columnMODI_DTM = new global::System.Data.DataColumn("MODI_DTM", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMODI_DTM);
                this.columnMODI_USER = new global::System.Data.DataColumn("MODI_USER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMODI_USER);
                this.columnPRODNO = new global::System.Data.DataColumn("PRODNO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPRODNO);
                this.columnPO_OE_NO = new global::System.Data.DataColumn("PO_OE_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPO_OE_NO);
                this.columnINV_APPROVAL_D_ID = new global::System.Data.DataColumn("INV_APPROVAL_D_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINV_APPROVAL_D_ID);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnINV_APPRO_IMEI_ID}, true));
                this.columnINV_APPRO_IMEI_ID.AllowDBNull = false;
                this.columnINV_APPRO_IMEI_ID.Unique = true;
                this.columnINV_APPRO_IMEI_ID.MaxLength = 32;
                this.columnIMEI.MaxLength = 50;
                this.columnCREATE_USER.MaxLength = 20;
                this.columnMODI_USER.MaxLength = 20;
                this.columnPRODNO.AllowDBNull = false;
                this.columnPRODNO.MaxLength = 20;
                this.columnPO_OE_NO.AllowDBNull = false;
                this.columnPO_OE_NO.MaxLength = 32;
                this.columnINV_APPROVAL_D_ID.AllowDBNull = false;
                this.columnINV_APPROVAL_D_ID.MaxLength = 32;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public INV_APPRO_IMEIRow NewINV_APPRO_IMEIRow() {
                return ((INV_APPRO_IMEIRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new INV_APPRO_IMEIRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(INV_APPRO_IMEIRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.INV_APPRO_IMEIRowChanged != null)) {
                    this.INV_APPRO_IMEIRowChanged(this, new INV_APPRO_IMEIRowChangeEvent(((INV_APPRO_IMEIRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.INV_APPRO_IMEIRowChanging != null)) {
                    this.INV_APPRO_IMEIRowChanging(this, new INV_APPRO_IMEIRowChangeEvent(((INV_APPRO_IMEIRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.INV_APPRO_IMEIRowDeleted != null)) {
                    this.INV_APPRO_IMEIRowDeleted(this, new INV_APPRO_IMEIRowChangeEvent(((INV_APPRO_IMEIRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.INV_APPRO_IMEIRowDeleting != null)) {
                    this.INV_APPRO_IMEIRowDeleting(this, new INV_APPRO_IMEIRowChangeEvent(((INV_APPRO_IMEIRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveINV_APPRO_IMEIRow(INV_APPRO_IMEIRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                PROD_IMEI_DTO ds = new PROD_IMEI_DTO();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "INV_APPRO_IMEIDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class INV_APPRO_IMEI_TEMPDataTable : global::System.Data.TypedTableBase<INV_APPRO_IMEI_TEMPRow> {
            
            private global::System.Data.DataColumn columnTEMP_ID;
            
            private global::System.Data.DataColumn columnIMEI;
            
            private global::System.Data.DataColumn columnCREATE_USER;
            
            private global::System.Data.DataColumn columnCREATE_DTM;
            
            private global::System.Data.DataColumn columnMODI_DTM;
            
            private global::System.Data.DataColumn columnMODI_USER;
            
            private global::System.Data.DataColumn columnPRODNO;
            
            private global::System.Data.DataColumn columnPO_OE_NO;
            
            private global::System.Data.DataColumn columnINV_APPROVAL_D_ID;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public INV_APPRO_IMEI_TEMPDataTable() {
                this.TableName = "INV_APPRO_IMEI_TEMP";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal INV_APPRO_IMEI_TEMPDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected INV_APPRO_IMEI_TEMPDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TEMP_IDColumn {
                get {
                    return this.columnTEMP_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IMEIColumn {
                get {
                    return this.columnIMEI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CREATE_USERColumn {
                get {
                    return this.columnCREATE_USER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CREATE_DTMColumn {
                get {
                    return this.columnCREATE_DTM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MODI_DTMColumn {
                get {
                    return this.columnMODI_DTM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MODI_USERColumn {
                get {
                    return this.columnMODI_USER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PRODNOColumn {
                get {
                    return this.columnPRODNO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PO_OE_NOColumn {
                get {
                    return this.columnPO_OE_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn INV_APPROVAL_D_IDColumn {
                get {
                    return this.columnINV_APPROVAL_D_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public INV_APPRO_IMEI_TEMPRow this[int index] {
                get {
                    return ((INV_APPRO_IMEI_TEMPRow)(this.Rows[index]));
                }
            }
            
            public event INV_APPRO_IMEI_TEMPRowChangeEventHandler INV_APPRO_IMEI_TEMPRowChanging;
            
            public event INV_APPRO_IMEI_TEMPRowChangeEventHandler INV_APPRO_IMEI_TEMPRowChanged;
            
            public event INV_APPRO_IMEI_TEMPRowChangeEventHandler INV_APPRO_IMEI_TEMPRowDeleting;
            
            public event INV_APPRO_IMEI_TEMPRowChangeEventHandler INV_APPRO_IMEI_TEMPRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddINV_APPRO_IMEI_TEMPRow(INV_APPRO_IMEI_TEMPRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public INV_APPRO_IMEI_TEMPRow AddINV_APPRO_IMEI_TEMPRow(string TEMP_ID, string IMEI, string CREATE_USER, System.DateTime CREATE_DTM, System.DateTime MODI_DTM, string MODI_USER, string PRODNO, string PO_OE_NO, string INV_APPROVAL_D_ID) {
                INV_APPRO_IMEI_TEMPRow rowINV_APPRO_IMEI_TEMPRow = ((INV_APPRO_IMEI_TEMPRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        TEMP_ID,
                        IMEI,
                        CREATE_USER,
                        CREATE_DTM,
                        MODI_DTM,
                        MODI_USER,
                        PRODNO,
                        PO_OE_NO,
                        INV_APPROVAL_D_ID};
                rowINV_APPRO_IMEI_TEMPRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowINV_APPRO_IMEI_TEMPRow);
                return rowINV_APPRO_IMEI_TEMPRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public INV_APPRO_IMEI_TEMPRow FindByTEMP_ID(string TEMP_ID) {
                return ((INV_APPRO_IMEI_TEMPRow)(this.Rows.Find(new object[] {
                            TEMP_ID})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                INV_APPRO_IMEI_TEMPDataTable cln = ((INV_APPRO_IMEI_TEMPDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new INV_APPRO_IMEI_TEMPDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnTEMP_ID = base.Columns["TEMP_ID"];
                this.columnIMEI = base.Columns["IMEI"];
                this.columnCREATE_USER = base.Columns["CREATE_USER"];
                this.columnCREATE_DTM = base.Columns["CREATE_DTM"];
                this.columnMODI_DTM = base.Columns["MODI_DTM"];
                this.columnMODI_USER = base.Columns["MODI_USER"];
                this.columnPRODNO = base.Columns["PRODNO"];
                this.columnPO_OE_NO = base.Columns["PO_OE_NO"];
                this.columnINV_APPROVAL_D_ID = base.Columns["INV_APPROVAL_D_ID"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnTEMP_ID = new global::System.Data.DataColumn("TEMP_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTEMP_ID);
                this.columnIMEI = new global::System.Data.DataColumn("IMEI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIMEI);
                this.columnCREATE_USER = new global::System.Data.DataColumn("CREATE_USER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREATE_USER);
                this.columnCREATE_DTM = new global::System.Data.DataColumn("CREATE_DTM", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREATE_DTM);
                this.columnMODI_DTM = new global::System.Data.DataColumn("MODI_DTM", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMODI_DTM);
                this.columnMODI_USER = new global::System.Data.DataColumn("MODI_USER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMODI_USER);
                this.columnPRODNO = new global::System.Data.DataColumn("PRODNO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPRODNO);
                this.columnPO_OE_NO = new global::System.Data.DataColumn("PO_OE_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPO_OE_NO);
                this.columnINV_APPROVAL_D_ID = new global::System.Data.DataColumn("INV_APPROVAL_D_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINV_APPROVAL_D_ID);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnTEMP_ID}, true));
                this.columnTEMP_ID.AllowDBNull = false;
                this.columnTEMP_ID.Unique = true;
                this.columnTEMP_ID.MaxLength = 32;
                this.columnIMEI.MaxLength = 50;
                this.columnCREATE_USER.MaxLength = 20;
                this.columnMODI_USER.MaxLength = 20;
                this.columnPRODNO.AllowDBNull = false;
                this.columnPRODNO.MaxLength = 20;
                this.columnPO_OE_NO.AllowDBNull = false;
                this.columnPO_OE_NO.MaxLength = 32;
                this.columnINV_APPROVAL_D_ID.AllowDBNull = false;
                this.columnINV_APPROVAL_D_ID.MaxLength = 32;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public INV_APPRO_IMEI_TEMPRow NewINV_APPRO_IMEI_TEMPRow() {
                return ((INV_APPRO_IMEI_TEMPRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new INV_APPRO_IMEI_TEMPRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(INV_APPRO_IMEI_TEMPRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.INV_APPRO_IMEI_TEMPRowChanged != null)) {
                    this.INV_APPRO_IMEI_TEMPRowChanged(this, new INV_APPRO_IMEI_TEMPRowChangeEvent(((INV_APPRO_IMEI_TEMPRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.INV_APPRO_IMEI_TEMPRowChanging != null)) {
                    this.INV_APPRO_IMEI_TEMPRowChanging(this, new INV_APPRO_IMEI_TEMPRowChangeEvent(((INV_APPRO_IMEI_TEMPRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.INV_APPRO_IMEI_TEMPRowDeleted != null)) {
                    this.INV_APPRO_IMEI_TEMPRowDeleted(this, new INV_APPRO_IMEI_TEMPRowChangeEvent(((INV_APPRO_IMEI_TEMPRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.INV_APPRO_IMEI_TEMPRowDeleting != null)) {
                    this.INV_APPRO_IMEI_TEMPRowDeleting(this, new INV_APPRO_IMEI_TEMPRowChangeEvent(((INV_APPRO_IMEI_TEMPRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveINV_APPRO_IMEI_TEMPRow(INV_APPRO_IMEI_TEMPRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                PROD_IMEI_DTO ds = new PROD_IMEI_DTO();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "INV_APPRO_IMEI_TEMPDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class INV_APPRO_IMEIRow : global::System.Data.DataRow {
            
            private INV_APPRO_IMEIDataTable tableINV_APPRO_IMEI;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal INV_APPRO_IMEIRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableINV_APPRO_IMEI = ((INV_APPRO_IMEIDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string INV_APPRO_IMEI_ID {
                get {
                    return ((string)(this[this.tableINV_APPRO_IMEI.INV_APPRO_IMEI_IDColumn]));
                }
                set {
                    this[this.tableINV_APPRO_IMEI.INV_APPRO_IMEI_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string IMEI {
                get {
                    try {
                        return ((string)(this[this.tableINV_APPRO_IMEI.IMEIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'INV_APPRO_IMEI\' 中資料行 \'IMEI\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableINV_APPRO_IMEI.IMEIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CREATE_USER {
                get {
                    try {
                        return ((string)(this[this.tableINV_APPRO_IMEI.CREATE_USERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'INV_APPRO_IMEI\' 中資料行 \'CREATE_USER\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableINV_APPRO_IMEI.CREATE_USERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime CREATE_DTM {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableINV_APPRO_IMEI.CREATE_DTMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'INV_APPRO_IMEI\' 中資料行 \'CREATE_DTM\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableINV_APPRO_IMEI.CREATE_DTMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime MODI_DTM {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableINV_APPRO_IMEI.MODI_DTMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'INV_APPRO_IMEI\' 中資料行 \'MODI_DTM\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableINV_APPRO_IMEI.MODI_DTMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string MODI_USER {
                get {
                    try {
                        return ((string)(this[this.tableINV_APPRO_IMEI.MODI_USERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'INV_APPRO_IMEI\' 中資料行 \'MODI_USER\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableINV_APPRO_IMEI.MODI_USERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PRODNO {
                get {
                    return ((string)(this[this.tableINV_APPRO_IMEI.PRODNOColumn]));
                }
                set {
                    this[this.tableINV_APPRO_IMEI.PRODNOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PO_OE_NO {
                get {
                    return ((string)(this[this.tableINV_APPRO_IMEI.PO_OE_NOColumn]));
                }
                set {
                    this[this.tableINV_APPRO_IMEI.PO_OE_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string INV_APPROVAL_D_ID {
                get {
                    return ((string)(this[this.tableINV_APPRO_IMEI.INV_APPROVAL_D_IDColumn]));
                }
                set {
                    this[this.tableINV_APPRO_IMEI.INV_APPROVAL_D_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIMEINull() {
                return this.IsNull(this.tableINV_APPRO_IMEI.IMEIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIMEINull() {
                this[this.tableINV_APPRO_IMEI.IMEIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCREATE_USERNull() {
                return this.IsNull(this.tableINV_APPRO_IMEI.CREATE_USERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCREATE_USERNull() {
                this[this.tableINV_APPRO_IMEI.CREATE_USERColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCREATE_DTMNull() {
                return this.IsNull(this.tableINV_APPRO_IMEI.CREATE_DTMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCREATE_DTMNull() {
                this[this.tableINV_APPRO_IMEI.CREATE_DTMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMODI_DTMNull() {
                return this.IsNull(this.tableINV_APPRO_IMEI.MODI_DTMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMODI_DTMNull() {
                this[this.tableINV_APPRO_IMEI.MODI_DTMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMODI_USERNull() {
                return this.IsNull(this.tableINV_APPRO_IMEI.MODI_USERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMODI_USERNull() {
                this[this.tableINV_APPRO_IMEI.MODI_USERColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class INV_APPRO_IMEI_TEMPRow : global::System.Data.DataRow {
            
            private INV_APPRO_IMEI_TEMPDataTable tableINV_APPRO_IMEI_TEMP;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal INV_APPRO_IMEI_TEMPRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableINV_APPRO_IMEI_TEMP = ((INV_APPRO_IMEI_TEMPDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TEMP_ID {
                get {
                    return ((string)(this[this.tableINV_APPRO_IMEI_TEMP.TEMP_IDColumn]));
                }
                set {
                    this[this.tableINV_APPRO_IMEI_TEMP.TEMP_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string IMEI {
                get {
                    try {
                        return ((string)(this[this.tableINV_APPRO_IMEI_TEMP.IMEIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'INV_APPRO_IMEI_TEMP\' 中資料行 \'IMEI\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableINV_APPRO_IMEI_TEMP.IMEIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CREATE_USER {
                get {
                    try {
                        return ((string)(this[this.tableINV_APPRO_IMEI_TEMP.CREATE_USERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'INV_APPRO_IMEI_TEMP\' 中資料行 \'CREATE_USER\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableINV_APPRO_IMEI_TEMP.CREATE_USERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime CREATE_DTM {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableINV_APPRO_IMEI_TEMP.CREATE_DTMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'INV_APPRO_IMEI_TEMP\' 中資料行 \'CREATE_DTM\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableINV_APPRO_IMEI_TEMP.CREATE_DTMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime MODI_DTM {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableINV_APPRO_IMEI_TEMP.MODI_DTMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'INV_APPRO_IMEI_TEMP\' 中資料行 \'MODI_DTM\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableINV_APPRO_IMEI_TEMP.MODI_DTMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string MODI_USER {
                get {
                    try {
                        return ((string)(this[this.tableINV_APPRO_IMEI_TEMP.MODI_USERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("資料表 \'INV_APPRO_IMEI_TEMP\' 中資料行 \'MODI_USER\' 的值是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableINV_APPRO_IMEI_TEMP.MODI_USERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PRODNO {
                get {
                    return ((string)(this[this.tableINV_APPRO_IMEI_TEMP.PRODNOColumn]));
                }
                set {
                    this[this.tableINV_APPRO_IMEI_TEMP.PRODNOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PO_OE_NO {
                get {
                    return ((string)(this[this.tableINV_APPRO_IMEI_TEMP.PO_OE_NOColumn]));
                }
                set {
                    this[this.tableINV_APPRO_IMEI_TEMP.PO_OE_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string INV_APPROVAL_D_ID {
                get {
                    return ((string)(this[this.tableINV_APPRO_IMEI_TEMP.INV_APPROVAL_D_IDColumn]));
                }
                set {
                    this[this.tableINV_APPRO_IMEI_TEMP.INV_APPROVAL_D_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIMEINull() {
                return this.IsNull(this.tableINV_APPRO_IMEI_TEMP.IMEIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIMEINull() {
                this[this.tableINV_APPRO_IMEI_TEMP.IMEIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCREATE_USERNull() {
                return this.IsNull(this.tableINV_APPRO_IMEI_TEMP.CREATE_USERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCREATE_USERNull() {
                this[this.tableINV_APPRO_IMEI_TEMP.CREATE_USERColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCREATE_DTMNull() {
                return this.IsNull(this.tableINV_APPRO_IMEI_TEMP.CREATE_DTMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCREATE_DTMNull() {
                this[this.tableINV_APPRO_IMEI_TEMP.CREATE_DTMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMODI_DTMNull() {
                return this.IsNull(this.tableINV_APPRO_IMEI_TEMP.MODI_DTMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMODI_DTMNull() {
                this[this.tableINV_APPRO_IMEI_TEMP.MODI_DTMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMODI_USERNull() {
                return this.IsNull(this.tableINV_APPRO_IMEI_TEMP.MODI_USERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMODI_USERNull() {
                this[this.tableINV_APPRO_IMEI_TEMP.MODI_USERColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class INV_APPRO_IMEIRowChangeEvent : global::System.EventArgs {
            
            private INV_APPRO_IMEIRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public INV_APPRO_IMEIRowChangeEvent(INV_APPRO_IMEIRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public INV_APPRO_IMEIRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class INV_APPRO_IMEI_TEMPRowChangeEvent : global::System.EventArgs {
            
            private INV_APPRO_IMEI_TEMPRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public INV_APPRO_IMEI_TEMPRowChangeEvent(INV_APPRO_IMEI_TEMPRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public INV_APPRO_IMEI_TEMPRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591